const autos = {
    "americanos": [
        { "id": 1, "marca": "Ford", "modelo": "Mustang Dark Horse", "img": "./Assent/US/Mustang-Dark-Horse.png", "precio": "$63,265", "categoria": "Muscle Car", "specs": "5.0L V8 N/A | 500 HP", "detail": { "motor": "5.0L Coyote V8 Gen 4", "tipo_motor": "Gasolina / Atmosférico", "aceleracion": "3.7s", "torque": "418 lb-ft", "transmision": "TREMEC 6-Vel", "tipo_transmision": "Manual", "frenos": "Brembo 6-Pistones", "consumo": "14 mpg", "medidas": "4.82m x 1.91m", "seguridad": "Ford Co-Pilot360", "airbags": "8 Airbags", "extra": "Enfriadores de aceite auxiliares" } },
        { "id": 2, "marca": "Chevrolet", "modelo": "Camaro ZL1 ", "img": "./Assent/US/Camaro-ZL1.png", "precio": "$88,000", "categoria": "Muscle Car", "specs": "6.2L V8 Supercharged | 650 HP", "detail": { "motor": "6.2L LT4 Supercharged V8", "tipo_motor": "Gasolina / Sobrealimentado", "aceleracion": "3.5s", "torque": "650 lb-ft", "transmision": "10-Vel Paddle Shift", "tipo_transmision": "Automática", "frenos": "Brembo Performance", "consumo": "13 mpg", "medidas": "4.78m x 1.89m", "seguridad": "StabiliTrak", "airbags": "8 Airbags", "extra": "Suspensión Magnetic Ride Control" } },
        { "id": 3, "marca": "Corvette", "modelo": "ZR1 C8 (2025)", "img": "./Assent/US/Corvette-ZR1-C8.png", "precio": "$150,000", "categoria": "Supercar", "specs": "5.5L V8 Twin-Turbo | 1,064 HP", "detail": { "motor": "5.5L LT7 Twin-Turbo V8", "tipo_motor": "Gasolina / Twin-Turbo", "aceleracion": "2.4s", "torque": "828 lb-ft", "transmision": "8-Vel DCT", "tipo_transmision": "Doble Embrague", "frenos": "Cerámicos de Carbono", "consumo": "11 mpg", "medidas": "4.69m x 2.02m", "seguridad": "Active Handling System", "airbags": "4 Airbags", "extra": "Turbocompresores gemelos simétricos" } },
        { "id": 4, "marca": "Dodge", "modelo": "Charger Daytona Scat Pack", "img": "./Assent/US/Charger-Daytona-Scat-Pack.png", "precio": "$73,190", "categoria": "Muscle Car", "specs": "Dual Motor Electric | 670 HP", "detail": { "motor": "Electric Drive Module 400V", "tipo_motor": "Eléctrico", "aceleracion": "3.3s", "torque": "627 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Brembo 6-Pistones", "consumo": "90 MPGe", "medidas": "5.24m x 2.02m", "seguridad": "Active Driving Assist", "airbags": "6 Airbags", "extra": "Escape Fratzonic Chambered" } },
        { "id": 5, "marca": "Shelby", "modelo": "Super Snake (2024)", "img": "./Assent/US/Shelby-Super-Snake.png", "precio": "$140,000", "categoria": "Muscle Car", "specs": "5.0L V8 Supercharged | 830 HP", "detail": { "motor": "5.0L Coyote w/ Whipple Supercharger", "tipo_motor": "Gasolina / Sobrealimentado", "aceleracion": "3.1s", "torque": "630 lb-ft", "transmision": "6-Vel Manual", "tipo_transmision": "Manual Short Throw", "frenos": "Shelby by Brembo", "consumo": "10 mpg", "medidas": "4.81m x 1.91m", "seguridad": "Refuerzos de chasis Shelby", "airbags": "8 Airbags", "extra": "Capó de aluminio ventilado" } },
        { "id": 6, "marca": "Ram", "modelo": "1500 RHO (2025)", "img": "./Assent/US/Ram-1500-RHO.png", "precio": "$69,995", "categoria": "Pickup", "specs": "3.0L I6 Hurricane | 540 HP", "detail": { "motor": "3.0L Hurricane H.O. Twin Turbo", "tipo_motor": "Gasolina / Twin-Turbo", "aceleracion": "4.6s", "torque": "521 lb-ft", "transmision": "8HP95 8-Vel", "tipo_transmision": "Automática", "frenos": "Discos 15' ventilados", "consumo": "15 mpg", "medidas": "5.91m x 2.23m", "seguridad": "Forward Collision Warning", "airbags": "6 Airbags", "extra": "Amortiguadores Bilstein Black Hawk e2" } },
        { "id": 7, "marca": "Hummer", "modelo": "EV Edition 1", "img": "./Assent/US/HummerEV.png", "precio": "$112,595", "categoria": "SUV", "specs": "Triple Motor | 1,000 HP", "detail": { "motor": "Ultium Drive System", "tipo_motor": "Eléctrico", "aceleracion": "3.0s", "torque": "11,500 lb-ft (Rueda)", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Discos Heavy Duty", "consumo": "47 MPGe", "medidas": "5.50m x 2.20m", "seguridad": "Super Cruise", "airbags": "6 Airbags", "extra": "Modo CrabWalk (Cangrejo)" } },
        { "id": 8, "marca": "Jeep", "modelo": "Wrangler Rubicon 392 Final Ed.", "img": "./Assent/US/Jeep392.png", "precio": "$99,995", "categoria": "SUV", "specs": "6.4L V8 HEMI | 470 HP", "detail": { "motor": "6.4L V8 HEMI SRT", "tipo_motor": "Gasolina / Atmosférico", "aceleracion": "4.5s", "torque": "470 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "Automática", "frenos": "Heavy Duty ABS", "consumo": "13 mpg", "medidas": "4.78m x 1.87m", "seguridad": "Blind Spot Monitoring", "airbags": "6 Airbags", "extra": "Cabrestante Warn de 8,000 lbs" } },
        { "id": 9, "marca": "Cadillac", "modelo": "Escalade-V (2025)", "img": "./Assent/US/EscaladeV.png", "precio": "$152,295", "categoria": "SUV", "specs": "6.2L V8 Supercharged | 682 HP", "detail": { "motor": "6.2L Supercharged V8 LT4", "tipo_motor": "Gasolina / Sobrealimentado", "aceleracion": "4.4s", "torque": "653 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Brembo High Performance", "consumo": "11 mpg", "medidas": "5.38m x 2.06m", "seguridad": "Night Vision System", "airbags": "8 Airbags", "extra": "Pantalla OLED curva de 38'" } },
        { "id": 10, "marca": "Cadillac", "modelo": "CT5-V Blackwing", "img": "./Assent/US/CT5Blackwing.png", "precio": "$93,495", "categoria": "Sedan", "specs": "6.2L V8 Supercharged | 668 HP", "detail": { "motor": "6.2L V8 LT4 Hand-Built", "tipo_motor": "Gasolina / Sobrealimentado", "aceleracion": "3.4s", "torque": "659 lb-ft", "transmision": "6-Vel Manual", "tipo_transmision": "Manual / Rev-Match", "frenos": "Carbon Ceramic opcionales", "consumo": "13 mpg", "medidas": "4.94m x 1.88m", "seguridad": "Magnetic Ride 4.0", "airbags": "8 Airbags", "extra": "Data Recorder de rendimiento" } },
        { "id": 11, "marca": "Ford", "modelo": "F-150 Raptor R", "img": "./Assent/US/F-150-Raptor-R.png", "precio": "$110,000", "categoria": "Pickup", "specs": "5.2L V8 Supercharged | 720 HP", "detail": { "motor": "5.2L V8 Predator", "tipo_motor": "Gasolina / Sobrealimentado", "aceleracion": "3.7s", "torque": "640 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos Heavy Duty", "consumo": "12 mpg", "medidas": "5.90m x 2.43m", "seguridad": "Terrain Management", "airbags": "6 Airbags", "extra": "Amortiguadores Fox Live Valve" } },
        { "id": 12, "marca": "Dodge", "modelo": "Durango SRT Hellcat", "img": "./Assent/US/DurangoHellcat.png", "precio": "$95,995", "categoria": "SUV", "specs": "6.2L V8 Supercharged | 710 HP", "detail": { "motor": "6.2L HEMI Hellcat V8", "tipo_motor": "Gasolina / Sobrealimentado", "aceleracion": "3.5s", "torque": "645 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "TorqueFlite", "frenos": "Brembo 6-Pistones", "consumo": "12 mpg", "medidas": "5.10m x 1.94m", "seguridad": "AWD Performance Tuned", "airbags": "7 Airbags", "extra": "Capacidad de remolque 8,700 lbs" } },
        { "id": 13, "marca": "Corvette", "modelo": "E-Ray C8", "img": "./Assent/US/Corvette-E-Ray-C8.png", "precio": "$104,900", "categoria": "Supercar", "specs": "6.2L V8 Hybrid | 655 HP", "detail": { "motor": "6.2L LT2 V8 + Motor Eléctrico", "tipo_motor": "Híbrido AWD", "aceleracion": "2.5s", "torque": "595 lb-ft", "transmision": "8-Vel DCT", "tipo_transmision": "Doble Embrague", "frenos": "Carbon Ceramic", "consumo": "19 mpg", "medidas": "4.69m x 2.02m", "seguridad": "All-Season Performance Tires", "airbags": "4 Airbags", "extra": "Primer Corvette de tracción total" } },
        { "id": 14, "marca": "Chevrolet", "modelo": "Silverado EV RST", "img": "./Assent/US/SilveradoEV.png", "precio": "$105,000", "categoria": "Pickup", "specs": "Dual Motor Electric | 754 HP", "detail": { "motor": "Ultium Electric Drive", "tipo_motor": "Eléctrico", "aceleracion": "4.5s", "torque": "785 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Regenerativos", "consumo": "80 MPGe", "medidas": "5.92m x 2.10m", "seguridad": "Super Cruise", "airbags": "6 Airbags", "extra": "Dirección en las 4 ruedas" } },
        { "id": 15, "marca": "Ford", "modelo": "Mustang GTD (2025)", "img": "./Assent/US/Mustang-GTD.png", "precio": "$325,000", "categoria": "Supercar", "specs": "5.2L V8 Supercharged | 800+ HP", "detail": { "motor": "5.2L Supercharged V8", "tipo_motor": "Gasolina / Sobrealimentado", "aceleracion": "3.0s", "torque": "N/A", "transmision": "8-Vel DCT Trasera", "tipo_transmision": "Transeje", "frenos": "Carbon Ceramic", "consumo": "10 mpg", "medidas": "4.85m x 2.00m", "seguridad": "Track-Focused ESC", "airbags": "6 Airbags", "extra": "Suspensión adaptativa de carrera" } },
        { "id": 16, "marca": "Jeep", "modelo": "Grand Wagoneer L", "img": "./Assent/US/GrandWagoneer.png", "precio": "$91,000", "categoria": "SUV", "specs": "3.0L I6 Hurricane | 510 HP", "detail": { "motor": "Hurricane Twin Turbo 510", "tipo_motor": "Gasolina / Twin-Turbo", "aceleracion": "5.9s", "torque": "500 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos 4 ruedas", "consumo": "17 mpg", "medidas": "5.75m x 2.12m", "seguridad": "Active Driving Assist", "airbags": "8 Airbags", "extra": "Sonido McIntosh 23 altavoces" } },
        { "id": 17, "marca": "Cadillac", "modelo": "LYRIQ-V", "img": "./Assent/US/LyriqV.png", "precio": "$78,000", "categoria": "SUV", "specs": "Dual Motor Electric | 550 HP", "detail": { "motor": "Ultium AWD", "tipo_motor": "Eléctrico", "aceleracion": "4.1s", "torque": "524 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Brembo", "consumo": "89 MPGe", "medidas": "4.99m x 1.97m", "seguridad": "Enhanced Automatic Parking", "airbags": "8 Airbags", "extra": "Suspensión deportiva V-Series" } },
        { "id": 18, "marca": "Shelby", "modelo": "F-150 Shelby Centennial", "img": "./Assent/US/Shelby-F-150-Centennial.png", "precio": "$135,000", "categoria": "Pickup", "specs": "5.0L V8 Supercharged | 800 HP", "detail": { "motor": "5.0L Coyote w/ Shelby Blower", "tipo_motor": "Gasolina / Sobrealimentado", "aceleracion": "3.9s", "torque": "680 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Shelby Performance Brakes", "consumo": "11 mpg", "medidas": "5.89m x 2.03m", "seguridad": "Refuerzos de carga", "airbags": "6 Airbags", "extra": "Interior de piel Centennial Edition" } },
        { "id": 19, "marca": "Chevrolet", "modelo": "Corvette Z06 C8", "img": "./Assent/US/Corvette-Z06-C8.png", "precio": "$112,700", "categoria": "Supercar", "specs": "5.5L V8 N/A | 670 HP", "detail": { "motor": "5.5L LT6 Flat-Plane Crank", "tipo_motor": "Gasolina / Atmosférico", "aceleracion": "2.6s", "torque": "460 lb-ft", "transmision": "8-Vel DCT", "tipo_transmision": "Doble Embrague", "frenos": "Brembo 6-Pistones", "consumo": "14 mpg", "medidas": "4.68m x 2.02m", "seguridad": "Performance Traction", "airbags": "4 Airbags", "extra": "Línea roja a 8,600 RPM" } },
        { "id": 20, "marca": "Ram", "modelo": "1500 Tungsten (2025)", "img": "./Assent/US/Ram-1500-Tungsten.png", "precio": "$87,155", "categoria": "Pickup", "specs": "3.0L I6 Hurricane | 540 HP", "detail": { "motor": "Hurricane H.O. Twin-Turbo", "tipo_motor": "Gasolina / Twin-Turbo", "aceleracion": "4.8s", "torque": "521 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "Automática", "frenos": "ABS Premium", "consumo": "17 mpg", "medidas": "5.91m x 2.08m", "seguridad": "Hands-Free Driving Assist", "airbags": "6 Airbags", "extra": "Asientos de masaje con 24 posiciones" } },
        { "id": 21, "marca": "Ford", "modelo": "Bronco Raptor", "img": "./Assent/US/BroncoRaptor.png", "precio": "$90,035", "categoria": "SUV", "specs": "3.0L V6 Twin-Turbo | 418 HP", "detail": { "motor": "3.0L EcoBoost V6", "tipo_motor": "Gasolina / Twin-Turbo", "aceleracion": "5.6s", "torque": "440 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos 4 ruedas", "consumo": "15 mpg", "medidas": "4.85m x 2.17m", "seguridad": "GOAT Modes", "airbags": "6 Airbags", "extra": "Amortiguadores Fox 3.1 Live Valve" } },
        { "id": 22, "marca": "Dodge", "modelo": "Charger Sixpack (2025)", "img": "./Assent/US/Changer-Sixpack.png", "precio": "$55,000", "categoria": "Muscle Car", "specs": "3.0L I6 Twin-Turbo | 550 HP", "detail": { "motor": "3.0L Hurricane H.O.", "tipo_motor": "Gasolina / Twin-Turbo", "aceleracion": "3.8s", "torque": "500 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "Automática", "frenos": "Performance Brakes", "consumo": "18 mpg", "medidas": "5.24m x 2.02m", "seguridad": "Lane Keep Assist", "airbags": "6 Airbags", "extra": "Tracción AWD de serie" } },
        { "id": 23, "marca": "Cadillac", "modelo": "CELESTIQ", "img": "./Assent/US/Celestiq.png", "precio": "$340,000", "categoria": "Sedan", "specs": "Dual Motor Electric | 600 HP", "detail": { "motor": "Ultium High Performance", "tipo_motor": "Eléctrico", "aceleracion": "3.8s", "torque": "640 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Brembo", "consumo": "N/A", "medidas": "5.50m x 2.10m", "seguridad": "Ultra Cruise", "airbags": "10 Airbags", "extra": "Techo de cristal inteligente dividido" } },
        { "id": 24, "marca": "Jeep", "modelo": "Recon EV (2025)", "img": "./Assent/US/JeepRecon.png", "precio": "$60,000", "categoria": "SUV", "specs": "Dual Motor Electric | 600 HP", "detail": { "motor": "Electric AWD System", "tipo_motor": "Eléctrico", "aceleracion": "3.5s", "torque": "N/A", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Regenerativos", "consumo": "95 MPGe", "medidas": "4.50m x 1.90m", "seguridad": "Selec-Terrain EV", "airbags": "6 Airbags", "extra": "Puertas removibles y techo abierto" } },
        { "id": 25, "marca": "Hummer", "modelo": "EV SUV 3X", "img": "./Assent/US/HummerEVSUV.png", "precio": "$106,945", "categoria": "SUV", "specs": "Triple Motor | 830 HP", "detail": { "motor": "Ultium e4WD", "tipo_motor": "Eléctrico", "aceleracion": "3.5s", "torque": "11,500 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "ABS Off-road", "consumo": "53 MPGe", "medidas": "5.00m x 2.20m", "seguridad": "Super Cruise", "airbags": "6 Airbags", "extra": "Extracción Mode (Aumenta altura 6')" } },
        { "id": 26, "marca": "Chevrolet", "modelo": "Blazer EV SS", "img": "./Assent/US/BlazerEVSS.png", "precio": "$65,995", "categoria": "SUV", "specs": "Dual Motor Electric | 557 HP", "detail": { "motor": "Performance AWD", "tipo_motor": "Eléctrico", "aceleracion": "3.9s", "torque": "648 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Brembo", "consumo": "96 MPGe", "medidas": "4.88m x 1.98m", "seguridad": "Chevy Safety Assist", "airbags": "8 Airbags", "extra": "Modo WOW (Wide Open Watts)" } },
        { "id": 27, "marca": "Ford", "modelo": "Explorer ST (2025)", "img": "./Assent/US/ExplorerST.png", "precio": "$55,000", "categoria": "SUV", "specs": "3.0L V6 Twin-Turbo | 400 HP", "detail": { "motor": "3.0L EcoBoost V6", "tipo_motor": "Gasolina / Twin-Turbo", "aceleracion": "5.2s", "torque": "415 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Performance Brakes (Rojos)", "consumo": "20 mpg", "medidas": "5.05m x 2.00m", "seguridad": "BlueCruise 1.2", "airbags": "7 Airbags", "extra": "Suspensión deportiva ST" } },
        { "id": 28, "marca": "Corvette", "modelo": "Stingray C8 Z51", "img": "./Assent/US/Corvette-Stingray-C8.png", "precio": "$69,995", "categoria": "Supercar", "specs": "6.2L V8 N/A | 495 HP", "detail": { "motor": "6.2L LT2 V8", "tipo_motor": "Gasolina / Atmosférico", "aceleracion": "2.9s", "torque": "470 lb-ft", "transmision": "8-Vel DCT", "tipo_transmision": "Doble Embrague", "frenos": "Brembo Z51", "consumo": "19 mpg", "medidas": "4.63m x 1.93m", "seguridad": "Rear Park Assist", "airbags": "4 Airbags", "extra": "Motor central por primera vez" } },
        { "id": 29, "marca": "Ram", "modelo": "2500 Power Wagon", "img": "./Assent/US/Ram-2500-Power-Wagon.png", "precio": "$71,000", "categoria": "Pickup", "specs": "6.4L V8 HEMI | 410 HP", "detail": { "motor": "6.4L HEMI V8 SRT", "tipo_motor": "Gasolina / Atmosférico", "aceleracion": "7.5s", "torque": "429 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos Heavy Duty", "consumo": "12 mpg", "medidas": "6.06m x 2.12m", "seguridad": "Hill Descent Control", "airbags": "6 Airbags", "extra": "Winche Warn Zeon-12 de fábrica" } },
        { "id": 30, "marca": "Jeep", "modelo": "Gladiator Mojave", "img": "./Assent/US/Gladiator-Mojave.png", "precio": "$52,000", "categoria": "Pickup", "specs": "3.6L V6 N/A | 285 HP", "detail": { "motor": "3.6L Pentastar V6", "tipo_motor": "Gasolina", "aceleracion": "7.2s", "torque": "260 lb-ft", "transmision": "6-Vel Manual", "tipo_transmision": "Manual", "frenos": "ABS Off-road", "consumo": "19 mpg", "medidas": "5.54m x 1.87m", "seguridad": "Desert Rated Badge", "airbags": "4 Airbags", "extra": "Amortiguadores Fox 2.5 Bypass" } },
        { "id": 31, "marca": "Cadillac", "modelo": "XT6 Sport", "img": "./Assent/US/XT6Sport.png", "precio": "$61,000", "categoria": "SUV", "specs": "3.6L V6 N/A | 310 HP", "detail": { "motor": "3.6L V6 con VVT", "tipo_motor": "Gasolina", "aceleracion": "6.9s", "torque": "271 lb-ft", "transmision": "9-Vel Auto", "tipo_transmision": "Automática", "frenos": "Brembo frontales", "consumo": "21 mpg", "medidas": "5.04m x 1.96m", "seguridad": "Night Vision", "airbags": "7 Airbags", "extra": "Chasis deportivo con Twin-Clutch" } },
        { "id": 32, "marca": "Shelby", "modelo": "Shelby GT-H", "img": "./Assent/US/ShelbyGTH.png", "precio": "$85,000", "categoria": "Muscle Car", "specs": "5.0L V8 N/A | 480 HP", "detail": { "motor": "5.0L Coyote tuned", "tipo_motor": "Gasolina", "aceleracion": "4.2s", "torque": "420 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Ford Performance", "consumo": "15 mpg", "medidas": "4.79m x 1.91m", "seguridad": "Stability Control", "airbags": "8 Airbags", "extra": "Colores clásicos Hertz Gold/Black" } },
        { "id": 33, "marca": "Chevrolet", "modelo": "Tahoe RST (2025)", "img": "./Assent/US/TahoeRST.png", "precio": "$72,000", "categoria": "SUV", "specs": "6.2L V8 N/A | 420 HP", "detail": { "motor": "6.2L Ecotec3 V8", "tipo_motor": "Gasolina", "aceleracion": "5.8s", "torque": "460 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos ventilados", "consumo": "16 mpg", "medidas": "5.35m x 2.06m", "seguridad": "Buckle to Drive", "airbags": "7 Airbags", "extra": "Suspensión neumática adaptativa" } },
        { "id": 34, "marca": "Ford", "modelo": "Ranger Raptor", "img": "./Assent/US/Ranger-Raptor.png", "precio": "$57,065", "categoria": "Pickup", "specs": "3.0L V6 Twin-Turbo | 405 HP", "detail": { "motor": "3.0L EcoBoost V6", "tipo_motor": "Gasolina / Twin-Turbo", "aceleracion": "5.3s", "torque": "430 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos ventilados", "consumo": "17 mpg", "medidas": "5.36m x 2.03m", "seguridad": "Trail Turn Assist", "airbags": "7 Airbags", "extra": "Modo de escape activo" } },
        { "id": 35, "marca": "Dodge", "modelo": "Hornet R/T", "img": "./Assent/US/HornetRT.png", "precio": "$41,000", "categoria": "SUV", "specs": "1.3L Turbo Hybrid | 288 HP", "detail": { "motor": "1.3L MultiAir Turbo + Electric", "tipo_motor": "Híbrido Enchufable (PHEV)", "aceleracion": "5.6s", "torque": "383 lb-ft", "transmision": "6-Vel Auto", "tipo_transmision": "Automática", "frenos": "Brembo 4-Pistones", "consumo": "77 MPGe", "medidas": "4.53m x 1.84m", "seguridad": "Traffic Sign Recognition", "airbags": "7 Airbags", "extra": "Función PowerShot (+25 HP)" } },
        { "id": 36, "marca": "Cadillac", "modelo": "OPTIMIQ (2025)", "img": "./Assent/US/Optimiq.png", "precio": "$54,000", "categoria": "SUV", "specs": "Dual Motor Electric | 300 HP", "detail": { "motor": "Ultium AWD", "tipo_motor": "Eléctrico", "aceleracion": "6.0s", "torque": "354 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Regenerativos", "consumo": "98 MPGe", "medidas": "4.82m x 1.90m", "seguridad": "Google Built-in", "airbags": "8 Airbags", "extra": "Sonido AKG Studio 19 altavoces" } },
        { "id": 37, "marca": "Jeep", "modelo": "Wagoneer S (2025)", "img": "./Assent/US/WagoneerS.png", "precio": "$71,000", "categoria": "SUV", "specs": "Dual Motor Electric | 600 HP", "detail": { "motor": "BEV AWD System", "tipo_motor": "Eléctrico", "aceleracion": "3.4s", "torque": "617 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "High Performance ABS", "consumo": "92 MPGe", "medidas": "4.88m x 1.90m", "seguridad": "Active Driving Assist", "airbags": "8 Airbags", "extra": "Techo solar panorámico de serie" } },
        { "id": 38, "marca": "Chevrolet", "modelo": "Colorado ZR2 Bison", "img": "./Assent/US/Colorado-ZR2-Bison.png", "precio": "$60,500", "categoria": "Pickup", "specs": "2.7L I4 Turbo | 310 HP", "detail": { "motor": "2.7L Turbo High-Output", "tipo_motor": "Gasolina / Turbo", "aceleracion": "6.8s", "torque": "430 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "Automática", "frenos": "AEV Brakes", "consumo": "16 mpg", "medidas": "5.41m x 1.90m", "seguridad": "Bloqueo diferencial elect.", "airbags": "6 Airbags", "extra": "Protección de bajos AEV de boro" } },
        { "id": 39, "marca": "Ford", "modelo": "F-150 Lightning Platinum", "img": "./Assent/US/LightningPlatinum.png", "precio": "$85,000", "categoria": "SUV", "specs": "Dual Motor Electric | 580 HP", "detail": { "motor": "Dual Electric Motors", "tipo_motor": "Eléctrico", "aceleracion": "4.0s", "torque": "775 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Regenerativos", "consumo": "70 MPGe", "medidas": "5.91m x 2.03m", "seguridad": "Pro Trailer Hitch Assist", "airbags": "6 Airbags", "extra": "Pro Power Onboard (9.6 kW)" } },
        { "id": 40, "marca": "Ram", "modelo": "1500 REV (2025)", "img": "./Assent/US/RamREV.png", "precio": "$75,000", "categoria": "SUV", "specs": "Dual Motor Electric | 654 HP", "detail": { "motor": "Dual 250 kW EDM", "tipo_motor": "Eléctrico", "aceleracion": "4.4s", "torque": "620 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Regenerativos Heavy Duty", "consumo": "N/A", "medidas": "5.91m x 2.08m", "seguridad": "ParkSense Pro", "airbags": "6 Airbags", "extra": "Autonomía proyectada de 500 millas" } },
        { "id": 41, "marca": "Chevrolet", "modelo": "Equinox EV RS", "img": "./Assent/US/EquinoxEV.png", "precio": "$44,000", "categoria": "SUV", "specs": "Dual Motor Electric | 290 HP", "detail": { "motor": "Ultium FWD/AWD", "tipo_motor": "Eléctrico", "aceleracion": "5.9s", "torque": "346 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "ABS Regenerativo", "consumo": "108 MPGe", "medidas": "4.83m x 1.91m", "seguridad": "Super Cruise", "airbags": "8 Airbags", "extra": "Pantalla de infoentretenimiento 17.7'" } },
        { "id": 42, "marca": "Ford", "modelo": "Mustang Mach-E Rally", "img": "./Assent/US/MachERally.png", "precio": "$60,000", "categoria": "SUV", "specs": "Dual Motor Electric | 480 HP", "detail": { "motor": "Electric AWD Tuned", "tipo_motor": "Eléctrico", "aceleracion": "3.4s", "torque": "650 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Brembo 385mm", "consumo": "85 MPGe", "medidas": "4.74m x 1.88m", "seguridad": "RallySport Drive Mode", "airbags": "8 Airbags", "extra": "Spoiler trasero estilo Focus RS" } },
        { "id": 43, "marca": "Jeep", "modelo": "Grand Cherokee 4xe Trailhawk", "img": "./Assent/US/GrandCherokee4xe.png", "precio": "$66,000", "categoria": "SUV", "specs": "2.0L Turbo Hybrid | 375 HP", "detail": { "motor": "2.0L I4 + 2 Motores Eléctricos", "tipo_motor": "Híbrido Enchufable", "aceleracion": "6.0s", "torque": "470 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos ventilados", "consumo": "56 MPGe", "medidas": "4.91m x 1.96m", "seguridad": "Quadra-Drive II AWD", "airbags": "8 Airbags", "extra": "Barra estabilizadora desconectable" } },
        { "id": 44, "marca": "Cadillac", "modelo": "Escalade IQ (2025)", "img": "./Assent/US/EscaladeIQ.png", "precio": "$130,000", "categoria": "SUV", "specs": "Dual Motor Electric | 750 HP", "detail": { "motor": "Ultium 200 kWh", "tipo_motor": "Eléctrico", "aceleracion": "5.0s", "torque": "785 lb-ft", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Regenerativos", "consumo": "N/A", "medidas": "5.69m x 2.38m", "seguridad": "Arrival Mode (CrabWalk)", "airbags": "8 Airbags", "extra": "Pantalla LED de 55 pulgadas" } },
        { "id": 45, "marca": "Chevrolet", "modelo": "Corvette Z06 GT3.R", "img": "./Assent/US/Z06GT3R.png", "precio": "$600,000", "categoria": "Supercar", "specs": "5.5L V8 N/A | 600 HP", "detail": { "motor": "5.5L LT6 Race-Spec", "tipo_motor": "Gasolina", "aceleracion": "N/A", "torque": "N/A", "transmision": "6-Vel Secuencial", "tipo_transmision": "Carreras", "frenos": "AP Racing Performance", "consumo": "N/A", "medidas": "4.70m x 2.04m", "seguridad": "Jaula FIA", "airbags": "0 Airbags", "extra": "Versión solo para pista (Customer Racing)" } },
        { "id": 46, "marca": "Dodge", "modelo": "Durango R/T Premium", "img": "./Assent/US/DurangoRT.png", "precio": "$63,000", "categoria": "SUV", "specs": "5.7L V8 HEMI | 360 HP", "detail": { "motor": "5.7L HEMI V8 VVT", "tipo_motor": "Gasolina", "aceleracion": "6.2s", "torque": "390 lb-ft", "transmision": "8-Vel Auto", "tipo_transmision": "Automática", "frenos": "Heavy Duty ABS", "consumo": "17 mpg", "medidas": "5.10m x 1.92m", "seguridad": "Blind Spot Assist", "airbags": "7 Airbags", "extra": "Sonido Harman Kardon 19 altavoces" } },
        { "id": 47, "marca": "Ford", "modelo": "Mustang GT Performance", "img": "./Assent/US/MustangGT.png", "precio": "$50,000", "categoria": "Muscle Car", "specs": "5.0L V8 N/A | 486 HP", "detail": { "motor": "5.0L Coyote V8", "tipo_motor": "Gasolina", "aceleracion": "4.2s", "torque": "415 lb-ft", "transmision": "6-Vel Manual", "tipo_transmision": "Manual", "frenos": "Brembo Pack", "consumo": "15 mpg", "medidas": "4.81m x 1.91m", "seguridad": "Electronic Drift Brake", "airbags": "8 Airbags", "extra": "Freno de mano electrónico para drift" } },
        { "id": 48, "marca": "Ram", "modelo": "2500 Rebel", "img": "./Assent/US/Ram-2500-Rebel.png", "precio": "$68,000", "categoria": "Pickup", "specs": "6.7L Cummins Turbo Diesel | 370 HP", "detail": { "motor": "6.7L I6 Cummins", "tipo_motor": "Diesel / Turbo", "aceleracion": "8.5s", "torque": "850 lb-ft", "transmision": "6-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos Heavy Duty", "consumo": "14 mpg", "medidas": "6.05m x 2.12m", "seguridad": "Rear Air Suspension", "airbags": "6 Airbags", "extra": "Capacidad de remolque off-road" } },
        { "id": 49, "marca": "Cadillac", "modelo": "VISTIQ (2026)", "img": "./Assent/US/Vistiq.png", "precio": "$85,000", "categoria": "SUV", "specs": "Dual Motor Electric | 615 HP", "detail": { "motor": "Ultium AWD High Power", "tipo_motor": "Eléctrico", "aceleracion": "4.0s", "torque": "N/A", "transmision": "Single Speed", "tipo_transmision": "Directa", "frenos": "Regenerativos", "consumo": "N/A", "medidas": "5.20m x 2.05m", "seguridad": "Super Cruise", "airbags": "8 Airbags", "extra": "Tres filas de asientos eléctricas" } },
        { "id": 50, "marca": "Chevrolet", "modelo": "Silverado 1500 ZR2", "img": "./Assent/US/Silverado-1500-Zr2.png", "precio": "$70,000", "categoria": "Pickup", "specs": "6.2L V8 N/A | 420 HP", "detail": { "motor": "6.2L V8 Ecotec3", "tipo_motor": "Gasolina", "aceleracion": "5.9s", "torque": "460 lb-ft", "transmision": "10-Vel Auto", "tipo_transmision": "Automática", "frenos": "Discos ventilados", "consumo": "15 mpg", "medidas": "5.89m x 2.06m", "seguridad": "Multimatic DSSV Dampers", "airbags": "6 Airbags", "extra": "Parachoques de acero de alta proximidad" } }
    ],

    "japoneses": [
        {
            "id": 1,
            "marca": "Nissan",
            "modelo": "Skyline GT-R R34 V-Spec II",
            "img": "./Assent/JDM/Skyline-R34.png",
            "precio": "$210,000",
            "categoria": "Deportivo",
            "specs": "2.6L I6 Twin-Turbo | 280 HP (Stock)",
            "detail": {
                "motor": "RB26DETT",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "4.9s",
                "torque": "289 lb-ft",
                "transmision": "Getrag 6-Vel",
                "tipo_transmision": "Manual",
                "frenos": "Brembo 4-Pistones",
                "consumo": "18 mpg",
                "medidas": "4.60m x 1.78m",
                "seguridad": "ATTESA E-TS Pro AWD",
                "airbags": "2 Airbags",
                "extra": "Pantalla multifunción MFD (Data)"
            }
        },
        {
            "id": 2,
            "marca": "Toyota",
            "modelo": "Supra MK4 A80",
            "img": "./Assent/JDM/Supra-MK4.png",
            "precio": "$180,000",
            "categoria": "Deportivo",
            "specs": "3.0L I6 Twin-Turbo | 320 HP",
            "detail": {
                "motor": "2JZ-GTE",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "4.6s",
                "torque": "315 lb-ft",
                "transmision": "V160 6-Vel",
                "tipo_transmision": "Manual",
                "frenos": "Discos ventilados High-spec",
                "consumo": "17 mpg",
                "medidas": "4.52m x 1.81m",
                "seguridad": "Traction Control System",
                "airbags": "2 Airbags",
                "extra": "Alerón de fábrica estilo Basket-Handle"
            }
        },
        {
            "id": 3,
            "marca": "Mazda",
            "modelo": "RX-7 Spirit R Type A",
            "img": "./Assent/JDM/RX7-SpiritR.png",
            "precio": "$125,000",
            "categoria": "Deportivo",
            "specs": "1.3L Rotary Twin-Turbo | 276 HP",
            "detail": {
                "motor": "13B-REW Rotativo",
                "tipo_motor": "Gasolina / Rotativo Twin-Turbo",
                "aceleracion": "5.1s",
                "torque": "231 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos perforados",
                "consumo": "14 mpg",
                "medidas": "4.28m x 1.76m",
                "seguridad": "Chasis aligerado",
                "airbags": "2 Airbags",
                "extra": "Asientos Recaro de fibra de carbono rojos"
            }
        },
        {
            "id": 4,
            "marca": "Honda",
            "modelo": "NSX Type R (NA2)",
            "img": "./Assent/JDM/NSX-R.png",
            "precio": "$450,000",
            "categoria": "Deportivo",
            "specs": "3.2L V6 N/A | 290 HP",
            "detail": {
                "motor": "C32B VTEC",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "4.4s",
                "torque": "224 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo de alto rendimiento",
                "consumo": "19 mpg",
                "medidas": "4.40m x 1.81m",
                "seguridad": "ABS calibrado para pista",
                "airbags": "0 Airbags (Weight reduction)",
                "extra": "Capó de fibra de carbono ventilado"
            }
        },
        {
            "id": 5,
            "marca": "Nissan",
            "modelo": "GT-R Nismo (2024)",
            "img": "./Assent/JDM/GTR-Nismo-2024.png",
            "precio": "$210,900",
            "categoria": "Deportivo",
            "specs": "3.8L V6 Twin-Turbo | 600 HP",
            "detail": {
                "motor": "VR38DETT",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "2.5s",
                "torque": "481 lb-ft",
                "transmision": "6-Vel DCT",
                "tipo_transmision": "Doble Embrague",
                "frenos": "Cerámicos de Carbono",
                "consumo": "16 mpg",
                "medidas": "4.70m x 1.89m",
                "seguridad": "Advanced VDC System",
                "airbags": "6 Airbags",
                "extra": "Turbocompresores de GT3"
            }
        },
        {
            "id": 6,
            "marca": "Lexus",
            "modelo": "LFA Nürburgring Edition",
            "img": "./Assent/JDM/Lexus-LFA.png",
            "precio": "$1,100,000",
            "categoria": "Deportivo",
            "specs": "4.8L V10 N/A | 563 HP",
            "detail": {
                "motor": "1LR-GUE V10",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "3.6s",
                "torque": "354 lb-ft",
                "transmision": "6-Vel ASG",
                "tipo_transmision": "Secuencial",
                "frenos": "CCM (Carbon Ceramic)",
                "consumo": "12 mpg",
                "medidas": "4.50m x 1.89m",
                "seguridad": "VDIM (Vehicle Dynamics)",
                "airbags": "8 Airbags",
                "extra": "Sonido de motor afinado por Yamaha"
            }
        },
        {
            "id": 7,
            "marca": "Mitsubishi",
            "modelo": "Lancer Evolution IX MR",
            "img": "./Assent/JDM/Evo-IX.png",
            "precio": "$75,000",
            "categoria": "Sedan",
            "specs": "2.0L I4 Turbo | 286 HP",
            "detail": {
                "motor": "4G63T MIVEC",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "4.7s",
                "torque": "289 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo 4-Pistones",
                "consumo": "18 mpg",
                "medidas": "4.49m x 1.77m",
                "seguridad": "Super AYC (Active Yaw Control)",
                "airbags": "2 Airbags",
                "extra": "Techo de aluminio para bajar centro gravedad"
            }
        },
        {
            "id": 8,
            "marca": "Subaru",
            "modelo": "Impreza 22B STI",
            "img": "./Assent/JDM/Subaru-22B.png",
            "precio": "$300,000",
            "categoria": "Deportivo",
            "specs": "2.2L F4 Turbo | 280 HP",
            "detail": {
                "motor": "EJ22 Boxer Turbo",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "4.5s",
                "torque": "268 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "STI Performance",
                "consumo": "16 mpg",
                "medidas": "4.34m x 1.77m",
                "seguridad": "Symmetrical AWD",
                "airbags": "2 Airbags",
                "extra": "Carrocería ancha (Widebody) de fábrica"
            }
        },
        {
            "id": 9,
            "marca": "Toyota",
            "modelo": "GR Yaris RZ (2024)",
            "img": "./Assent/JDM/GR-Yaris.png",
            "precio": "$55,000",
            "categoria": "Deportivo",
            "specs": "1.6L I3 Turbo | 300 HP",
            "detail": {
                "motor": "G16E-GTS",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "4.8s",
                "torque": "295 lb-ft",
                "transmision": "GR-DAT 8-Vel",
                "tipo_transmision": "Automática / Manual",
                "frenos": "Discos de 356mm",
                "consumo": "25 mpg",
                "medidas": "3.99m x 1.80m",
                "seguridad": "GR-FOUR AWD System",
                "airbags": "6 Airbags",
                "extra": "Techo de polímero reforzado con fibra de carbono"
            }
        },
        {
            "id": 10,
            "marca": "Nissan",
            "modelo": "Silvia S15 Spec-R",
            "img": "./Assent/JDM/Silvia-S15.png",
            "precio": "$60,000",
            "categoria": "Deportivo",
            "specs": "2.0L I4 Turbo | 250 HP",
            "detail": {
                "motor": "SR20DET",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "5.5s",
                "torque": "202 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos ventilados",
                "consumo": "22 mpg",
                "medidas": "4.44m x 1.69m",
                "seguridad": "Helical LSD",
                "airbags": "2 Airbags",
                "extra": "Medidor de boost en pilar A"
            }
        },
        {
            "id": 11,
            "marca": "Honda",
            "modelo": "Civic Type R FL5 (2024)",
            "img": "./Assent/JDM/Civic-FL5.png",
            "precio": "$45,890",
            "categoria": "Deportivo",
            "specs": "2.0L I4 Turbo | 315 HP",
            "detail": {
                "motor": "K20C1 Turbo",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "5.3s",
                "torque": "310 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual / Rev-Match",
                "frenos": "Brembo 4-Pistones",
                "consumo": "24 mpg",
                "medidas": "4.59m x 1.89m",
                "seguridad": "Honda Sensing",
                "airbags": "10 Airbags",
                "extra": "Log LogR (Datalogger integrado)"
            }
        },
        {
            "id": 12,
            "marca": "Toyota",
            "modelo": "GR Supra A91-MT (2024)",
            "img": "./Assent/JDM/Supra-2024.png",
            "precio": "$59,000",
            "categoria": "Deportivo",
            "specs": "3.0L I6 Turbo | 382 HP",
            "detail": {
                "motor": "B58 Turbo",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "3.9s",
                "torque": "368 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo Performance",
                "consumo": "23 mpg",
                "medidas": "4.38m x 1.85m",
                "seguridad": "Pre-Collision System",
                "airbags": "8 Airbags",
                "extra": "Suspensión adaptativa variable"
            }
        },
        {
            "id": 13,
            "marca": "Nissan",
            "modelo": "Z Nismo (2024)",
            "img": "./Assent/JDM/Nissan-Z.png",
            "precio": "$65,000",
            "categoria": "Deportivo",
            "specs": "3.0L V6 Twin-Turbo | 420 HP",
            "detail": {
                "motor": "VR30DDTT",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "3.9s",
                "torque": "384 lb-ft",
                "transmision": "9-Vel Auto",
                "tipo_transmision": "Automática c/ Levas",
                "frenos": "Akebono 4-Pistones",
                "consumo": "20 mpg",
                "medidas": "4.38m x 1.84m",
                "seguridad": "Predictive Forward Collision",
                "airbags": "6 Airbags",
                "extra": "Llantas Dunlop SP Sport Maxx GT600"
            }
        },
        {
            "id": 14,
            "marca": "Honda",
            "modelo": "Integra Type R DC2",
            "img": "./Assent/JDM/Integra-DC2.png",
            "precio": "$50,000",
            "categoria": "Deportivo",
            "specs": "1.8L I4 N/A | 200 HP",
            "detail": {
                "motor": "B18C VTEC",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "6.2s",
                "torque": "131 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos ventilados",
                "consumo": "25 mpg",
                "medidas": "4.38m x 1.69m",
                "seguridad": "Helical LSD",
                "airbags": "2 Airbags",
                "extra": "Soldaduras de chasis reforzadas a mano"
            }
        },
        {
            "id": 15,
            "marca": "Mazda",
            "modelo": "MX-5 Miata ND3 (2024)",
            "img": "./Assent/JDM/Miata-ND3.png",
            "precio": "$30,000",
            "categoria": "Deportivo",
            "specs": "2.0L I4 N/A | 181 HP",
            "detail": {
                "motor": "Skyactiv-G 2.0",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "5.7s",
                "torque": "151 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo frontales",
                "consumo": "30 mpg",
                "medidas": "3.91m x 1.73m",
                "seguridad": "Kinematic Posture Control",
                "airbags": "4 Airbags",
                "extra": "Diferencial de deslizamiento limitado asimétrico"
            }
        },
        {
            "id": 16,
            "marca": "Mitsubishi",
            "modelo": "Lancer Evolution VI TME",
            "img": "./Assent/JDM/Evo-VI-TME.png",
            "precio": "$150,000",
            "categoria": "Sedan",
            "specs": "2.0L I4 Turbo | 280 HP",
            "detail": {
                "motor": "4G63 Turbo",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "4.4s",
                "torque": "275 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo Ralliart",
                "consumo": "15 mpg",
                "medidas": "4.35m x 1.77m",
                "seguridad": "Full-time 4WD",
                "airbags": "2 Airbags",
                "extra": "Turbocompresor de titanio (edición especial)"
            }
        },
        {
            "id": 17,
            "marca": "Subaru",
            "modelo": "WRX STI S209",
            "img": "./Assent/JDM/WRX-S209.png",
            "precio": "$100,000",
            "categoria": "Sedan",
            "specs": "2.5L F4 Turbo | 341 HP",
            "detail": {
                "motor": "EJ25 Boxer Turbo",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "4.4s",
                "torque": "330 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo 6-Pistones",
                "consumo": "17 mpg",
                "medidas": "4.60m x 1.84m",
                "seguridad": "DCCD AWD System",
                "airbags": "7 Airbags",
                "extra": "Intercooler water sprayer"
            }
        },
        {
            "id": 18,
            "marca": "Toyota",
            "modelo": "AE86 Sprinter Trueno",
            "img": "./Assent/JDM/AE86.png",
            "precio": "$45,000",
            "categoria": "Deportivo",
            "specs": "1.6L I4 N/A | 130 HP",
            "detail": {
                "motor": "4A-GE Blue Top",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "8.5s",
                "torque": "110 lb-ft",
                "transmision": "T50 5-Vel",
                "tipo_transmision": "Manual",
                "frenos": "Discos sólidos",
                "consumo": "28 mpg",
                "medidas": "4.20m x 1.63m",
                "seguridad": "Distribución 50/50",
                "airbags": "0 Airbags",
                "extra": "Icono mundial del Drift"
            }
        },
        {
            "id": 19,
            "marca": "Nissan",
            "modelo": "Skyline GT-R R32",
            "img": "./Assent/JDM/Skyline-R32.png",
            "precio": "$90,000",
            "categoria": "Deportivo",
            "specs": "2.6L I6 Twin-Turbo | 280 HP",
            "detail": {
                "motor": "RB26DETT",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "5.0s",
                "torque": "260 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos ventilados",
                "consumo": "16 mpg",
                "medidas": "4.54m x 1.75m",
                "seguridad": "ATTESA E-TS AWD",
                "airbags": "1 Airbag (opcional)",
                "extra": "Conocido como 'Godzilla' en Group A"
            }
        },
        {
            "id": 20,
            "marca": "Honda",
            "modelo": "S2000 AP2",
            "img": "./Assent/JDM/S2000.png",
            "precio": "$45,000",
            "categoria": "Deportivo",
            "specs": "2.2L I4 N/A | 240 HP",
            "detail": {
                "motor": "F22C1 VTEC",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "5.4s",
                "torque": "162 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual Corta",
                "frenos": "Discos 4 ruedas",
                "consumo": "22 mpg",
                "medidas": "4.12m x 1.75m",
                "seguridad": "VSA (Vehicle Stability)",
                "airbags": "2 Airbags",
                "extra": "Línea roja a las 8,000 RPM"
            }
        },
        {
            "id": 21,
            "marca": "Toyota",
            "modelo": "GR Corolla Circuit Ed.",
            "img": "./Assent/JDM/GR-Corolla.png",
            "precio": "$48,000",
            "categoria": "Deportivo",
            "specs": "1.6L I3 Turbo | 300 HP",
            "detail": {
                "motor": "G16E-GTS",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "4.9s",
                "torque": "273 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "4-Pistones Fijos",
                "consumo": "24 mpg",
                "medidas": "4.41m x 1.85m",
                "seguridad": "Toyota Safety Sense 3.0",
                "airbags": "10 Airbags",
                "extra": "Diferenciales Torsen Delantero/Trasero"
            }
        },
        {
            "id": 22,
            "marca": "Nissan",
            "modelo": "350Z Nismo",
            "img": "./Assent/JDM/Nissan-350Z.png",
            "precio": "$35,000",
            "categoria": "Deportivo",
            "specs": "3.5L V6 N/A | 306 HP",
            "detail": {
                "motor": "VQ35HR",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "5.2s",
                "torque": "268 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo Nismo",
                "consumo": "20 mpg",
                "medidas": "4.42m x 1.84m",
                "seguridad": "VDC Control",
                "airbags": "6 Airbags",
                "extra": "Chasis reforzado por Autech"
            }
        },
        {
            "id": 23,
            "marca": "Lexus",
            "modelo": "LC 500 Inspiration Series",
            "img": "./Assent/JDM/Lexus-LC500.png",
            "precio": "$115,000",
            "categoria": "Deportivo",
            "specs": "5.0L V8 N/A | 471 HP",
            "detail": {
                "motor": "2UR-GSE V8",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "4.4s",
                "torque": "398 lb-ft",
                "transmision": "10-Vel Direct Shift",
                "tipo_transmision": "Automática",
                "frenos": "Performance 6-Pistones",
                "consumo": "19 mpg",
                "medidas": "4.77m x 1.92m",
                "seguridad": "Lexus Safety System+",
                "airbags": "8 Airbags",
                "extra": "Techo de fibra de carbono"
            }
        },
        {
            "id": 24,
            "marca": "Mazda",
            "modelo": "RX-8 Spirit R",
            "img": "./Assent/JDM/RX8.png",
            "precio": "$28,000",
            "categoria": "Deportivo",
            "specs": "1.3L Rotary N/A | 232 HP",
            "detail": {
                "motor": "13B-MSP Renesis",
                "tipo_motor": "Gasolina / Rotativo",
                "aceleracion": "6.4s",
                "torque": "159 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos deportivos",
                "consumo": "16 mpg",
                "medidas": "4.42m x 1.77m",
                "seguridad": "Dynamic Stability Control",
                "airbags": "6 Airbags",
                "extra": "Puertas suicidas traseras de fábrica"
            }
        },
        {
            "id": 25,
            "marca": "Toyota",
            "modelo": "MR2 Turbo SW20",
            "img": "./Assent/JDM/MR2.png",
            "precio": "$32,000",
            "categoria": "Deportivo",
            "specs": "2.0L I4 Turbo | 200 HP",
            "detail": {
                "motor": "3S-GTE Turbo",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "5.8s",
                "torque": "200 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos ventilados",
                "consumo": "21 mpg",
                "medidas": "4.17m x 1.70m",
                "seguridad": "Motor Central Trasero",
                "airbags": "1 Airbag",
                "extra": "Conocido como el 'Baby Ferrari'"
            }
        },
        {
            "id": 26,
            "marca": "Honda",
            "modelo": "Civic Type R EK9",
            "img": "./Assent/JDM/Civic-EK9.png",
            "precio": "$42,000",
            "categoria": "Deportivo",
            "specs": "1.6L I4 N/A | 185 HP",
            "detail": {
                "motor": "B16B VTEC",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "6.7s",
                "torque": "118 lb-ft",
                "transmision": "5-Vel Manual c/ LSD",
                "tipo_transmision": "Manual",
                "frenos": "Discos Type R",
                "consumo": "26 mpg",
                "medidas": "4.18m x 1.69m",
                "seguridad": "Chasis aligerado",
                "airbags": "2 Airbags",
                "extra": "Alfombras rojas y pomo de titanio"
            }
        },
        {
            "id": 27,
            "marca": "Nissan",
            "modelo": "300ZX Twin Turbo",
            "img": "./Assent/JDM/300ZX.png",
            "precio": "$38,000",
            "categoria": "Deportivo",
            "specs": "3.0L V6 Twin-Turbo | 300 HP",
            "detail": {
                "motor": "VG30DETT",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "5.2s",
                "torque": "283 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "4-Pistones aluminio",
                "consumo": "18 mpg",
                "medidas": "4.52m x 1.80m",
                "seguridad": "Super HICAS (4-wheel steer)",
                "airbags": "1 Airbag",
                "extra": "Techo T-Top removible"
            }
        },
        {
            "id": 28,
            "marca": "Toyota",
            "modelo": "GR86 Premium (2024)",
            "img": "./Assent/JDM/GR86.png",
            "precio": "$33,000",
            "categoria": "Deportivo",
            "specs": "2.4L F4 N/A | 228 HP",
            "detail": {
                "motor": "Boxer FA24",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "6.1s",
                "torque": "184 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos 11.6'",
                "consumo": "25 mpg",
                "medidas": "4.26m x 1.77m",
                "seguridad": "Eyesight Assist",
                "airbags": "7 Airbags",
                "extra": "Diferencial Torsen de serie"
            }
        },
        {
            "id": 29,
            "marca": "Mitsubishi",
            "modelo": "3000GT VR-4",
            "img": "./Assent/JDM/3000GT.png",
            "precio": "$45,000",
            "categoria": "Deportivo",
            "specs": "3.0L V6 Twin-Turbo | 320 HP",
            "detail": {
                "motor": "6G72 Twin-Turbo",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "4.8s",
                "torque": "315 lb-ft",
                "transmision": "Getrag 6-Vel",
                "tipo_transmision": "Manual",
                "frenos": "Discos ventilados",
                "consumo": "16 mpg",
                "medidas": "4.56m x 1.84m",
                "seguridad": "AWD + AWS (All-Wheel Steer)",
                "airbags": "2 Airbags",
                "extra": "Aerodinámica activa delantera/trasera"
            }
        },
        {
            "id": 30,
            "marca": "Subaru",
            "modelo": "BRZ tS (2024)",
            "img": "./Assent/JDM/BRZ-ts.png",
            "precio": "$36,000",
            "categoria": "Deportivo",
            "specs": "2.4L F4 N/A | 228 HP",
            "detail": {
                "motor": "Boxer FA24 Tuned",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "6.0s",
                "torque": "184 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo Gold",
                "consumo": "25 mpg",
                "medidas": "4.26m x 1.77m",
                "seguridad": "EyeSight for Manual",
                "airbags": "7 Airbags",
                "extra": "Suspensión Hitachi adaptativa"
            }
        },
        {
            "id": 31,
            "marca": "Toyota",
            "modelo": "Celica GT-Four ST205",
            "img": "./Assent/JDM/Celica-GT4.png",
            "precio": "$40,000",
            "categoria": "Deportivo",
            "specs": "2.0L I4 Turbo | 255 HP",
            "detail": {
                "motor": "3S-GTE Gen 3",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "5.9s",
                "torque": "224 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos ventilados",
                "consumo": "20 mpg",
                "medidas": "4.42m x 1.75m",
                "seguridad": "AWD Full-time",
                "airbags": "1 Airbag",
                "extra": "Capó con entrada de aire rally"
            }
        },
        {
            "id": 32,
            "marca": "Honda",
            "modelo": "NSX Type S (2022)",
            "img": "./Assent/JDM/NSX-S-2022.png",
            "precio": "$171,000",
            "categoria": "Supercar",
            "specs": "3.5L V6 Hybrid TT | 600 HP",
            "detail": {
                "motor": "V6 Twin-Turbo + 3 Motores Eléctricos",
                "tipo_motor": "Híbrido / Twin-Turbo",
                "aceleracion": "2.9s",
                "torque": "492 lb-ft",
                "transmision": "9-Vel DCT",
                "tipo_transmision": "Doble Embrague",
                "frenos": "Carbon Ceramic",
                "consumo": "21 mpg",
                "medidas": "4.53m x 1.94m",
                "seguridad": "SH-AWD (Super Handling)",
                "airbags": "8 Airbags",
                "extra": "Limitado a 350 unidades en el mundo"
            }
        },
        {
            "id": 33,
            "marca": "Nissan",
            "modelo": "Silvia S14 Kouki",
            "img": "./Assent/JDM/Silvia-S14.png",
            "precio": "$35,000",
            "categoria": "Deportivo",
            "specs": "2.0L I4 Turbo | 220 HP",
            "detail": {
                "motor": "SR20DET",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "6.3s",
                "torque": "203 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos 4 ruedas",
                "consumo": "22 mpg",
                "medidas": "4.50m x 1.73m",
                "seguridad": "Limited Slip Diff",
                "airbags": "1 Airbag",
                "extra": "Frente tipo 'Angry eyes' agresivo"
            }
        },
        {
            "id": 34,
            "marca": "Toyota",
            "modelo": "Chaser JZX100 Tourer V",
            "img": "./Assent/JDM/Chaser-JZX100.png",
            "precio": "$30,000",
            "categoria": "Sedan",
            "specs": "2.5L I6 Turbo | 280 HP",
            "detail": {
                "motor": "1JZ-GTE VVTi",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "5.6s",
                "torque": "280 lb-ft",
                "transmision": "R154 5-Vel",
                "tipo_transmision": "Manual",
                "frenos": "Discos ventilados",
                "consumo": "18 mpg",
                "medidas": "4.71m x 1.75m",
                "seguridad": "VSC Control",
                "airbags": "2 Airbags",
                "extra": "El sedán preferido para Drift en Japón"
            }
        },
        {
            "id": 35,
            "marca": "Mitsubishi",
            "modelo": "Lancer Evolution X Final Ed.",
            "img": "./Assent/JDM/Evo-X.png",
            "precio": "$55,000",
            "categoria": "Sedan",
            "specs": "2.0L I4 Turbo | 303 HP",
            "detail": {
                "motor": "4B11T MIVEC",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "4.8s",
                "torque": "305 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo 2-Piece",
                "consumo": "19 mpg",
                "medidas": "4.50m x 1.81m",
                "seguridad": "S-AWC (Super All Wheel)",
                "airbags": "7 Airbags",
                "extra": "Último modelo de la estirpe Evolution"
            }
        },
        {
            "id": 36,
            "marca": "Nissan",
            "modelo": "GT-R R35 Track Edition",
            "img": "./Assent/JDM/GTR-R35.png",
            "precio": "$150,000",
            "categoria": "Deportivo",
            "specs": "3.8L V6 Twin-Turbo | 565 HP",
            "detail": {
                "motor": "VR38DETT",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "2.7s",
                "torque": "467 lb-ft",
                "transmision": "6-Vel DCT",
                "tipo_transmision": "Doble Embrague",
                "frenos": "Brembo monobloque",
                "consumo": "18 mpg",
                "medidas": "4.71m x 1.89m",
                "seguridad": "AWD inteligente",
                "airbags": "6 Airbags",
                "extra": "Suspensión Bilstein Damptronic"
            }
        },
        {
            "id": 37,
            "marca": "Honda",
            "modelo": "Civic Type R EK9 Spoon",
            "img": "./Assent/JDM/EK9-Spoon.png",
            "precio": "$80,000",
            "categoria": "Deportivo",
            "specs": "1.6L I4 N/A | 195 HP",
            "detail": {
                "motor": "B16B Spoon Tuned",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "6.1s",
                "torque": "125 lb-ft",
                "transmision": "5-Vel Close Ratio",
                "tipo_transmision": "Manual",
                "frenos": "Spoon Monobloque",
                "consumo": "24 mpg",
                "medidas": "4.18m x 1.69m",
                "seguridad": "Jaula antivuelco",
                "airbags": "0 Airbags",
                "extra": "Colores icónicos Amarillo/Azul Spoon"
            }
        },
        {
            "id": 38,
            "marca": "Subaru",
            "modelo": "WRX TR (2024)",
            "img": "./Assent/JDM/WRX-2024.png",
            "precio": "$42,000",
            "categoria": "Sedan",
            "specs": "2.4L F4 Turbo | 271 HP",
            "detail": {
                "motor": "Boxer FA24F Turbo",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "5.4s",
                "torque": "258 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo 6-Pistones",
                "consumo": "22 mpg",
                "medidas": "4.67m x 1.82m",
                "seguridad": "EyeSight for Manual",
                "airbags": "7 Airbags",
                "extra": "Asientos Recaro Performance"
            }
        },
        {
            "id": 39,
            "marca": "Acura",
            "modelo": "Integra Type S (2024)",
            "img": "./Assent/JDM/Integra-TypeS.png",
            "precio": "$52,000",
            "categoria": "Deportivo",
            "specs": "2.0L I4 Turbo | 320 HP",
            "detail": {
                "motor": "K20C1 Turbo",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "5.1s",
                "torque": "310 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo 4-Pistones",
                "consumo": "24 mpg",
                "medidas": "4.72m x 1.90m",
                "seguridad": "AcuraWatch Assist",
                "airbags": "8 Airbags",
                "extra": "Escape central de triple salida"
            }
        },
        {
            "id": 40,
            "marca": "Toyota",
            "modelo": "Century GRMN",
            "img": "./Assent/JDM/Century-GRMN.png",
            "precio": "$200,000",
            "categoria": "Sedan",
            "specs": "5.0L V8 Hybrid | 425 HP",
            "detail": {
                "motor": "2UR-FSE V8 + Electric",
                "tipo_motor": "Híbrido",
                "aceleracion": "5.2s",
                "torque": "376 lb-ft",
                "transmision": "e-CVT Lujo",
                "tipo_transmision": "Automática",
                "frenos": "Discos Premium",
                "consumo": "32 mpg",
                "medidas": "5.33m x 1.93m",
                "seguridad": "Pre-Collision System",
                "airbags": "12 Airbags",
                "extra": "El coche del Emperador con toque deportivo"
            }
        },
        {
            "id": 41,
            "marca": "Nissan",
            "modelo": "Fairlady Z 432",
            "img": "./Assent/JDM/Z-432.png",
            "precio": "$250,000",
            "categoria": "Deportivo",
            "specs": "2.0L I6 N/A | 160 HP",
            "detail": {
                "motor": "S20 (GT-R Engine)",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "7.5s",
                "torque": "130 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos frontales",
                "consumo": "22 mpg",
                "medidas": "4.11m x 1.63m",
                "seguridad": "Distribución Clásica",
                "airbags": "0 Airbags",
                "extra": "Motor del Skyline GT-R en un chasis Z"
            }
        },
        {
            "id": 42,
            "marca": "Lexus",
            "modelo": "IS 500 F-Sport Performance",
            "img": "./Assent/JDM/Lexus-IS500.png",
            "precio": "$60,000",
            "categoria": "Sedan",
            "specs": "5.0L V8 N/A | 472 HP",
            "detail": {
                "motor": "2UR-GSE V8",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "4.4s",
                "torque": "395 lb-ft",
                "transmision": "8-Vel Sport Auto",
                "tipo_transmision": "Automática",
                "frenos": "Performance Brakes",
                "consumo": "20 mpg",
                "medidas": "4.76m x 1.84m",
                "seguridad": "Lexus Safety System+ 2.5",
                "airbags": "10 Airbags",
                "extra": "Escapes cuádruples en diagonal"
            }
        },
        {
            "id": 43,
            "marca": "Mazda",
            "modelo": "Mazda3 Turbo AWD (2024)",
            "img": "./Assent/JDM/Mazda3-Turbo.png",
            "precio": "$37,000",
            "categoria": "Sedan",
            "specs": "2.5L I4 Turbo | 250 HP",
            "detail": {
                "motor": "Skyactiv-G 2.5T",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "5.6s",
                "torque": "320 lb-ft",
                "transmision": "6-Vel Auto Sport",
                "tipo_transmision": "Automática",
                "frenos": "Discos ventilados",
                "consumo": "27 mpg",
                "medidas": "4.66m x 1.79m",
                "seguridad": "i-Activ AWD",
                "airbags": "7 Airbags",
                "extra": "Pintura Soul Red Crystal icónica"
            }
        },
        {
            "id": 44,
            "marca": "Suzuki",
            "modelo": "Jimny JB74 Wolf Edition",
            "img": "./Assent/JDM/Jimny.png",
            "precio": "$25,000",
            "categoria": "SUV",
            "specs": "1.5L I4 N/A | 102 HP",
            "detail": {
                "motor": "K15B",
                "tipo_motor": "Gasolina",
                "aceleracion": "12.0s",
                "torque": "96 lb-ft",
                "transmision": "5-Vel Manual",
                "tipo_transmision": "Manual c/ Reductora",
                "frenos": "Discos/Tambor Offroad",
                "consumo": "35 mpg",
                "medidas": "3.64m x 1.64m",
                "seguridad": "AllGrip Pro 4WD",
                "airbags": "6 Airbags",
                "extra": "Ejes rígidos para off-road puro"
            }
        },
        {
            "id": 45,
            "marca": "Subaru",
            "modelo": "Crosstrek Wilderness",
            "img": "./Assent/JDM/Crosstrek-Wilderness.png",
            "precio": "$32,000",
            "categoria": "SUV",
            "specs": "2.5L F4 N/A | 182 HP",
            "detail": {
                "motor": "Boxer FB25",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "8.1s",
                "torque": "178 lb-ft",
                "transmision": "Lineartronic CVT",
                "tipo_transmision": "Automática",
                "frenos": "ABS Off-road",
                "consumo": "27 mpg",
                "medidas": "4.48m x 1.80m",
                "seguridad": "EyeSight Driver Assist",
                "airbags": "7 Airbags",
                "extra": "Altura libre al suelo de 9.3 pulgadas"
            }
        },
        {
            "id": 46,
            "marca": "Honda",
            "modelo": "S660 Modulo X",
            "img": "./Assent/JDM/S660.png",
            "precio": "$30,000",
            "categoria": "Deportivo",
            "specs": "0.66L I3 Turbo | 64 HP",
            "detail": {
                "motor": "S07A Turbo Kei",
                "tipo_motor": "Gasolina / Turbo",
                "aceleracion": "10.0s",
                "torque": "77 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Discos pequeños",
                "consumo": "45 mpg",
                "medidas": "3.39m x 1.47m",
                "seguridad": "Motor Central Kei",
                "airbags": "4 Airbags",
                "extra": "El micro-deportivo de motor central"
            }
        },
        {
            "id": 47,
            "marca": "Toyota",
            "modelo": "Land Cruiser 300 GR Sport",
            "img": "./Assent/JDM/Land-Cruiser-300.png",
            "precio": "$85,000",
            "categoria": "SUV",
            "specs": "3.5L V6 Twin-Turbo | 409 HP",
            "detail": {
                "motor": "V35A-FTS",
                "tipo_motor": "Gasolina / Twin-Turbo",
                "aceleracion": "6.7s",
                "torque": "479 lb-ft",
                "transmision": "10-Vel Auto",
                "tipo_transmision": "Automática",
                "frenos": "Discos Heavy Duty",
                "consumo": "18 mpg",
                "medidas": "4.96m x 1.98m",
                "seguridad": "E-KDSS System",
                "airbags": "10 Airbags",
                "extra": "Tres bloqueos de diferencial"
            }
        },
        {
            "id": 48,
            "marca": "Nissan",
            "modelo": "Patrol NISMO",
            "img": "./Assent/JDM/Patrol-Nismo.png",
            "precio": "$105,000",
            "categoria": "SUV",
            "specs": "5.6L V8 N/A | 428 HP",
            "detail": {
                "motor": "VK56VD V8",
                "tipo_motor": "Gasolina",
                "aceleracion": "6.5s",
                "torque": "413 lb-ft",
                "transmision": "7-Vel Auto",
                "tipo_transmision": "Automática",
                "frenos": "Performance Brakes",
                "consumo": "14 mpg",
                "medidas": "5.16m x 1.99m",
                "seguridad": "Intelligent Cruise Control",
                "airbags": "8 Airbags",
                "extra": "Suspensión afinada por Bilstein"
            }
        },
        {
            "id": 49,
            "marca": "Honda",
            "modelo": "Civic Type R Mugen RR",
            "img": "./Assent/JDM/Mugen-RR.png",
            "precio": "$120,000",
            "categoria": "Deportivo",
            "specs": "2.0L I4 N/A | 240 HP",
            "detail": {
                "motor": "K20A Mugen Tuned",
                "tipo_motor": "Gasolina / Atmosférico",
                "aceleracion": "5.8s",
                "torque": "161 lb-ft",
                "transmision": "6-Vel Manual",
                "tipo_transmision": "Manual",
                "frenos": "Brembo Mugen",
                "consumo": "22 mpg",
                "medidas": "4.54m x 1.77m", "seguridad": "LSD Helicoidal", "airbags": "2 Airbags", "extra": "Solo 300 unidades en color Milano Red"
            }
        },
        { "id": 50, "marca": "Toyota", "modelo": "2000GT (1967)", "img": "./Assent/JDM/Toyota-2000GT.png", "precio": "$1,200,000", "categoria": "Deportivo", "specs": "2.0L I6 N/A | 150 HP", "detail": { "motor": "3M I6 Yamaha Tuned", "tipo_motor": "Gasolina", "aceleracion": "8.6s", "torque": "130 lb-ft", "transmision": "5-Vel Manual", "tipo_transmision": "Manual", "frenos": "Discos en 4 ruedas (Primero en Jp)", "consumo": "20 mpg", "medidas": "4.17m x 1.60m", "seguridad": "Distribución 49/51", "airbags": "0 Airbags", "extra": "El coche de James Bond en 'You Only Live Twice'" } }
    ]
}



export { autos };